#!/usr/bin/env bash
# configures new ubuntu machine by installing
# Nginx where it should be listening on port 80
# serve a page which would return a Hello World string


echo -e "Updating and installing Nginx.\n"
sudo apt-get update -y -qq && \
	 sudo apt-get install nginx -y

echo -e "\nSetting up some minor stuff.\n"

# start nginx service
sudo service nginx start

# allow nginx on the firewall
sudo ufw allow 'Nginx HTTP'

# give user ownership to website's files for easy editing
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# backup default index
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# create new index
echo -e "Hello World!" | dd status=none of=/var/www/html/index.nginx-debian.html

# restart nginx
sudo service nginx restart

echo -e "\nCompleted. ✅\n"
