#!/usr/bin/env bash
# A bash script which installs haproxy safely on ubuntu web server
# The first command installs software-properties-common package which helps
# you manage any PPAs you install - It’s probably already installed, but running
# it again ensures which it’s available - The second command puts the PPA into
# list of software sources
# Adding " =2.4.\* " to the end tells apt which we want to maintain the latest
# version of the HAProxy in the 2.4 branch

sudo apt install --no-install-recommends software-properties-common

sudo add-apt-repository ppa:vbernat/haproxy-2.4 -y

sudo apt install haproxy=2.4.\*
